DROP TABLE MEMBER

CREATE TABLE MEMBER(
ID BIGINT IDENTITY PRIMARY KEY,
LOGIN_ACCOUNT VARCHAR(50) NOT NULL UNIQUE,
PASSWORD VARCHAR(50) NOT NULL ,
NAME VARCHAR(40) NOT NULL, 
TYPE VARCHAR(20) NOT NULL,
EMAIL VARCHAR(50) ,
TEL VARCHAR(10) ,
MOBILE VARCHAR(10) 
)

INSERT INTO MEMBER (LOGIN_ACCOUNT, PASSWORD, NAME, TYPE, EMAIL)VALUES('sheila1112','asdf','sheila', 'P', 'sheila000@gmail.com')
INSERT INTO MEMBER (LOGIN_ACCOUNT, PASSWORD,NAME, TYPE, EMAIL)VALUES('anchor1112','asdf','anchor', 'P', 'anchor001@gmail.com')
INSERT INTO MEMBER (LOGIN_ACCOUNT, PASSWORD,NAME, TYPE, EMAIL)VALUES('jasmine1112','asdf','jasmine', 'P', 'jasmine002@gmail.com')

