use timebank
go


DROP TABLE TIME_LEDGER



CREATE TABLE TIME_LEDGER(
ID BIGINT IDENTITY PRIMARY KEY,
MEMBER_ID BIGINT NOT NULL,
TRANSACTION_TIME DATETIME NOT NULL,
DEPOSIT_VALUE INT,
WITHDRAWAL_VALUE INT,
BALANCE_VALUE INT NOT NULL,
DESCRIPTION VARCHAR(30) NOT NULL
)

INSERT INTO TIME_LEDGER (MEMBER_ID,TRANSACTION_TIME,DEPOSIT_VALUE,WITHDRAWAL_VALUE,BALANCE_VALUE,DESCRIPTION)
VALUES(1, '2018-11-11',100,0,100,'deposit')

INSERT INTO TIME_LEDGER (MEMBER_ID,TRANSACTION_TIME,DEPOSIT_VALUE,WITHDRAWAL_VALUE,BALANCE_VALUE,DESCRIPTION)
VALUES(1, '2018-11-11',50,150,0,'deposit')

INSERT INTO TIME_LEDGER (MEMBER_ID,TRANSACTION_TIME,DEPOSIT_VALUE,WITHDRAWAL_VALUE,BALANCE_VALUE,DESCRIPTION)
VALUES(2, '2018-11-11', 500, 500,0,'deposit')
