DROP TABLE ORDER_LIST

CREATE TABLE ORDER_LIST (
ID BIGINT IDENTITY PRIMARY KEY ,
REQUEST_LIST_ID BIGINT,
SUPPLIER_ID BIGINT,
REQUESTER_ID BIGINT,
SUPPLIER_ACCEPTION BIT,
SERVICE_CONFIRMATION BIT,
STATUS INT
)


INSERT INTO ORDER_LIST(REQUEST_LIST_ID,SUPPLIER_ID,REQUESTER_ID,SUPPLIER_ACCEPTION,SERVICE_CONFIRMATION, STATUS) 
VALUES(1, 1, 4, 0, 0, 3)

INSERT INTO ORDER_LIST(REQUEST_LIST_ID,SUPPLIER_ID,REQUESTER_ID,SUPPLIER_ACCEPTION,SERVICE_CONFIRMATION, STATUS) 
VALUES(2, 2, 3, 0, 0, 3)

INSERT INTO ORDER_LIST(REQUEST_LIST_ID,SUPPLIER_ID,REQUESTER_ID,SUPPLIER_ACCEPTION,SERVICE_CONFIRMATION, STATUS) 
VALUES(3, 2, 5, 0, 0, 3)