DROP TABLE ORG_MEMBER
DROP TABLE MEMBER

CREATE TABLE MEMBER(
ID BIGINT PRIMARY KEY IDENTITY ,
LOGIN_ACCOUNT VARCHAR(50) NOT NULL,
PASSWORD VARCHAR(50) NOT NULL ,
NAME VARCHAR(40) NOT NULL, 
TYPE VARCHAR(20) NOT NULL,
EMAIL VARCHAR(50) ,
TEL VARCHAR(10) ,
MOBILE VARCHAR(10) ,
CITY BIGINT,
FOREIGN KEY (CITY) REFERENCES AREA(ID)
)

INSERT INTO MEMBER ( LOGIN_ACCOUNT, PASSWORD, NAME, TYPE, EMAIL, CITY)VALUES('sheila1112','asdf','sheila', 'P', 'sheila000@gmail.com', 1)


--INSERT INTO MEMBER (ID, LOGIN_ACCOUNT, PASSWORD, NAME, TYPE, EMAIL, CITY)VALUES(1, 'sheila1112','asdf','sheila', 'P', 'sheila000@gmail.com', 1)
INSERT INTO MEMBER (LOGIN_ACCOUNT, PASSWORD,NAME, TYPE, EMAIL, CITY)VALUES('anchor1112','asdf','anchor', 'P', 'anchor001@gmail.com', 2)
INSERT INTO MEMBER (LOGIN_ACCOUNT, PASSWORD,NAME, TYPE, EMAIL, CITY)VALUES('jasmine1112','asdf','jasmine', 'P', 'jasmine002@gmail.com', 3)

