DROP TABLE AREA

CREATE TABLE AREA(
ID BIGINT PRIMARY KEY,
CITY VARCHAR(15) NOT NULL
)

INSERT INTO AREA VALUES (1, '基隆市')
INSERT INTO AREA VALUES (2, '台北市')
INSERT INTO AREA VALUES (3, '新北市')
INSERT INTO AREA VALUES (4, '桃園市')
INSERT INTO AREA VALUES (5, '新竹市')
INSERT INTO AREA VALUES (6, '新竹縣')