use TimeBank
DROP TABLE ORG_MEMBER

CREATE TABLE ORG_MEMBER (
ID BIGINT primary key ,
FOUNDER VARCHAR(20),
CEO VARCHAR(20)
FOREIGN KEY (ID) REFERENCES MEMBER(ID) 
)

--INSERT INTO ORG_MEMBER VALUES(29, '王老師', '魏雯祈')

INSERT INTO ORG_MEMBER  VALUES(1, 'Tom老師', '鄭正')
	